BEGIN;
	UPDATE fillfactor_100
	SET text_column = 'EDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBA'
	WHERE text_column = 'ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE';

	UPDATE fillfactor_90
	SET text_column = 'EDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBA'
	WHERE text_column = 'ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE';

	UPDATE fillfactor_75
	SET text_column = 'EDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBA'
	WHERE text_column = 'ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE';

	UPDATE fillfactor_50
	SET text_column = 'EDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBAEDCBA'
	WHERE text_column = 'ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE';

COMMIT;